In [1]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import AdaBoostClassifier

In [43]:
data=pd.read_csv('30_features.csv',index_col=0)

In [44]:
data.head()

,fulladdress_count_30,address_count_14,fulladdress_pct_increase_0_to_30,fulladdress_count_0_by_30,address_count_3,fulladdress_count_0_by_7,fulladdress_pct_increase_0_to_7,address_count_1,fulladdress_count_1,fulladdress_homephone_count_30,...,ssn_name_dob_count_14,ssn_firstname_count_0_by_30,ssn_firstname_pct_increase_0_to_30,ssn_lastname_count_0_by_30,fulladdress_homephone_pct_increase_0_to_30,fulladdress_homephone_count_0_by_30,address_pct_increase_1_to_14,dob_count_wSame_homephone_7,name_count_wSame_homephone_7,fraud_label
0,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,30.0,0.0,30.0,0.0,30.0,0.0,2,2,0
1,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,30.0,0.0,30.0,0.0,30.0,0.0,2,2,1
2,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,30.0,0.0,30.0,0.0,30.0,0.0,1,1,0
3,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,30.0,0.0,30.0,0.0,30.0,0.0,1,1,0
4,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,30.0,0.0,30.0,0.0,30.0,0.0,1,1,0

In [73]:
X=data.iloc[46749:833507,0:30].reset_index(drop=True)

In [74]:
#taking a look at the data
X

,fulladdress_count_30,address_count_14,fulladdress_pct_increase_0_to_30,fulladdress_count_0_by_30,address_count_3,fulladdress_count_0_by_7,fulladdress_pct_increase_0_to_7,address_count_1,fulladdress_count_1,fulladdress_homephone_count_30,...,name_dob_count_14,ssn_name_dob_count_14,ssn_firstname_count_0_by_30,ssn_firstname_pct_increase_0_to_30,ssn_lastname_count_0_by_30,fulladdress_homephone_pct_increase_0_to_30,fulladdress_homephone_count_0_by_30,address_pct_increase_1_to_14,dob_count_wSame_homephone_7,name_count_wSame_homephone_7
0,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,1,30.0,0.0,30.0,0.0,30.0,0.0,1,1
1,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,1,30.0,0.0,30.0,0.0,30.0,0.0,1,1
2,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,1,30.0,0.0,30.0,0.0,30.0,0.0,1,1
3,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,1,30.0,0.0,30.0,0.0,30.0,0.0,1,1
4,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,1,30.0,0.0,30.0,0.0,30.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786753,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,1,30.0,0.0,30.0,0.0,30.0,0.0,4,4
786754,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,1,30.0,0.0,30.0,0.0,30.0,0.0,4,4
786755,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,1,30.0,0.0,30.0,0.0,30.0,0.0,1,1
786756,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,1,30.0,0.0,30.0,0.0,30.0,0.0,4,4
786757,1,1,0.0,30.0,1,7.0,0.0,1,1,1,...,1,1,30.0,0.0,30.0,0.0,30.0,0.0,4,4

In [75]:
#specifying y 
y=data.iloc[46749:833507,30].reset_index(drop=True)

In [21]:
X_oot=data.iloc[833507:,0:30]

In [22]:
y_oot=data.iloc[833507:,30]

In [76]:
skf = StratifiedKFold(n_splits=10)

In [77]:
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [ 78606  78634  78678 ... 786755 786756 786757] TEST: [    0     1     2 ... 78675 78676 78677]
TRAIN: [     0      1      2 ... 786755 786756 786757] TEST: [ 78606  78634  78678 ... 172211 172349 172413]
TRAIN: [     0      1      2 ... 786755 786756 786757] TEST: [157162 157163 157164 ... 250739 250756 250832]
TRAIN: [     0      1      2 ... 786755 786756 786757] TEST: [235831 235832 235833 ... 330259 330318 330345]
TRAIN: [     0      1      2 ... 786755 786756 786757] TEST: [314507 314508 314509 ... 412582 412592 412603]
TRAIN: [     0      1      2 ... 786755 786756 786757] TEST: [393114 393115 393116 ... 488253 488356 488405]
TRAIN: [     0      1      2 ... 786755 786756 786757] TEST: [471808 471809 471810 ... 560096 560151 560152]
TRAIN: [     0      1      2 ... 786755 786756 786757] TEST: [550615 550616 550617 ... 632834 632912 632958]
TRAIN: [     0      1      2 ... 786755 786756 786757] TEST: [629326 629327 629328 ... 711637 711713 711744]
TRAIN: [     0      1      2 ... 711637 711713 711744] TEST: [708036 708037 708038 ... 786755 786756 786757]

In [26]:
clf = AdaBoostClassifier(n_estimators=100, random_state=0)

In [79]:
fdr=pd.DataFrame()

In [84]:
for train_index, test_index in skf.split(X, y):
    i=1
    X_train, X_test = X.iloc[train_index,:], X.iloc[test_index,:]
    y_train, y_test = y[train_index], y[test_index]
    clf.fit(X_train,y_train)
    X_trn_eval = X_train.copy()
    X_oot_eval = X_oot.copy()
    X_tst_eval = X_test.copy()
    X_trn_eval['predicted']=clf.predict_proba(X_train)[:,1]
    X_trn_eval['Fraud'] = y_train
    topRows = int(round(X_trn_eval.shape[0]*0.03))
    temp = X_trn_eval.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'Fraud']
    fdr.loc[i,'training']=sum(needed)/sum(X_trn_eval.loc[:,'Fraud'])
    
    X_tst_eval['predicted']=clf.predict_proba(X_test)[:,1]
    X_tst_eval['Fraud'] = y_test
    topRows = int(round(X_tst_eval.shape[0]*0.03))
    temp = X_tst_eval.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'Fraud']
    fdr.loc[i,'testing']=sum(needed)/sum(X_tst_eval.loc[:,'Fraud'])
    
    X_oot_eval['predicted']=clf.predict_proba(X_oot)[:,1]
    X_oot_eval['Fraud'] = y_oot
    topRows = int(round(X_oot_eval.shape[0]*0.03))
    temp = X_oot_eval.sort_values('predicted',ascending=False).head(topRows)
    needed = temp.loc[:,'Fraud']
    fdr.loc[i,'oot']=sum(needed)/sum(X_oot_eval.loc[:,'Fraud'])
    i=i+1
    avg_tr=fdr['training'].mean()
    avg_te=fdr['testing'].mean()
    avg_oot=fdrr['oot'].mean()

In [89]:
clf1 = AdaBoostClassifier(n_estimators=100, random_state=0,learning_rate=0.01)
clf1.fit(X_train,y_train)
X_trn_eval['predicted']=clf1.predict_proba(X_train)[:,1]
X_trn_eval['Fraud'] = y_train
topRows = int(round(X_trn_eval.shape[0]*0.03))
temp = X_trn_eval.sort_values('predicted',ascending=False).head(topRows)
needed = temp.loc[:,'Fraud']
fdr.loc[i,'training']=sum(needed)/sum(X_trn_eval.loc[:,'Fraud'])
    
X_tst_eval['predicted']=clf1.predict_proba(X_test)[:,1]

X_tst_eval['Fraud'] = y_test

topRows = int(round(X_tst_eval.shape[0]*0.03))

temp = X_tst_eval.sort_values('predicted',ascending=False).head(topRows)

needed = temp.loc[:,'Fraud']

fdr.loc[i,'testing']=sum(needed)/sum(X_tst_eval.loc[:,'Fraud'])
    

X_oot_eval['predicted']=clf1.predict_proba(X_oot)[:,1]

X_oot_eval['Fraud'] = y_oot

topRows = int(round(X_oot_eval.shape[0]*0.03))

temp = X_oot_eval.sort_values('predicted',ascending=False).head(topRows)

needed = temp.loc[:,'Fraud']

fdr.loc[i,'oot']=sum(needed)/sum(X_oot_eval.loc[:,'Fraud'])
avg_tr=fdr['training'].mean()
avg_te=fdr['testing'].mean()
avg_oot=fdrr['oot'].mean()

In [102]:
# more examples of changing different parameter, It is not all parameters I have chosen, I simplifies the notebook just to show 
# the intuition behind the loop
clf2 = AdaBoostClassifier(n_estimators=800, random_state=0,learning_rate=0.01)
clf2.fit(X_train,y_train)

X_trn_eval['predicted']=clf2.predict_proba(X_train)[:,1]
X_trn_eval['Fraud'] = y_train
topRows = int(round(X_trn_eval.shape[0]*0.03))
temp = X_trn_eval.sort_values('predicted',ascending=False).head(topRows)
needed = temp.loc[:,'Fraud']
fdr.loc[i,'training']=sum(needed)/sum(X_trn_eval.loc[:,'Fraud'])
    
X_tst_eval['predicted']=clf2.predict_proba(X_test)[:,1]

X_tst_eval['Fraud'] = y_test

topRows = int(round(X_tst_eval.shape[0]*0.03))

temp = X_tst_eval.sort_values('predicted',ascending=False).head(topRows)

needed = temp.loc[:,'Fraud']

fdr.loc[i,'testing']=sum(needed)/sum(X_tst_eval.loc[:,'Fraud'])
    

X_oot_eval['predicted']=clf2.predict_proba(X_oot)[:,1]

X_oot_eval['Fraud'] = y_oot

topRows = int(round(X_oot_eval.shape[0]*0.03))

temp = X_oot_eval.sort_values('predicted',ascending=False).head(topRows)

needed = temp.loc[:,'Fraud']

fdr.loc[i,'oot']=sum(needed)/sum(X_oot_eval.loc[:,'Fraud'])
avg_tr=fdr['training'].mean()
avg_te=fdr['testing'].mean()
avg_oot=fdrr['oot'].mean()

In [107]:
#final output: the parameters used is shown in the report.

   training   testing       oot
1  0.571666  0.574318  0.551970
2  0.540889  0.545295  0.522213
3  0.560918  0.554090  0.543168
4  0.565022  0.561126  0.543168
5  0.569419  0.570800  0.549874
6  0.558183  0.554969  0.537720
7  0.560625  0.554090  0.538139